- draft-patton-cfrg-vdaf.md
The authors of [BBCGGI21] have recently amended their paper to give the
protocol a proper name.
> Rename "Heavy Hitters" to "Poplar"

- draft-patton-cfrg-vdaf.md
- poc/flp.sage
- poc/prio3.sage
> prio3: Don't generate joint randomness if JOINT_RAND_LEN == 0

- draft-patton-cfrg-vdaf.md
Closes #13 by doing "rejection sampling". This an alternative to #29 and #30.
> Use "rejection sampling" for generating field elements

- draft-patton-cfrg-vdaf.md
Specifies a construction based on AES128. While pretty straight-forward,
this scheme uses CMAC, which is not widely used. We may want to provide
additional options in the future.
> Specify an instantiation of `Prg`

- poc/flp.sage
> fix duplicated JOINT_RAND_LEN

- draft-irtf-cfrg-vdaf.md
Closes #60.
This issue touches on a broader question, which is how to account for a
variety of different cryptographic techniques while minimizing burden
for applications. This question is tracked by #77.
> Close #60 by doing nothing

- draft-irtf-cfrg-vdaf.md
> Small editorial changes

- draft-irtf-cfrg-vdaf.md
- poc/field.sage
> Check that field elements are fully reduced while decoding

- poc/idpf.sage
- poc/idpf_poplar.sage
Noticed a typo in the poplar POC
> fix poc: "ipdf" instead of "idpf"

- poc/vdaf_prio3.sage
In Prio3, a single PRG is used to derive random coins for several different purposes. These are differentiated using a domain separation string "dst" and a single byte. This byte is set to the aggregator index when deriving joint randomness parts, and to 255 for joint randomness seeds and query randomness, but it is omitted for joint randomness and prover randomness. I propose to include this byte in every PRG call, and to set it to 254 for joint randomness, and 253 for query and prover randomness. This will help in the eventual modeling of the PRG as a random oracle (as in Issue [#106](https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/106).
> [poc] Prio3 improvements

- draft-irtf-cfrg-vdaf.md
- poc/vdaf_prio3.sage
All planned changes to Prio3 have been implemented in the reference code; propagate these changes to the document itself. Pick up some changes for Poplar1 as well.
Changes to the reference code were required in order to make it render nicely in the dcocument. However the algorithms themselves have not changed.
This change also breaks up the auxiliary functions sections into subsections: One for joint randomness computation, another for serialization, and a new subsection for enumerating the constants.
> Update spec to match reference code

- draft-irtf-cfrg-vdaf.md
Based on #143 (merge that first).
> Poplar1: Add an implementation note about "updating" the prefix tree

- poc/prg.sage
This updates the PRG test vector generation code to match changes made in #136.
> Fix PRG test vector generation

- draft-irtf-cfrg-vdaf.md
Based on #153 (merge that first).
* Remove a few out-of-date NOTEs
* Nit-pick the wording a bit
* Ack Hannah and Mike for security analysis
> Clean up security considerations a bit

- draft-irtf-cfrg-vdaf.md
> Update Change Log for 04

- draft-irtf-cfrg-vdaf.md
- poc/idpf_poplar.sage
> Spellcheck changes

- draft-irtf-cfrg-vdaf.md
Would have been nice to clean this up before 04 but 🤷
> Remove an out-of-date OPEN ISSUE

- draft-irtf-cfrg-vdaf.md
> Make a note about merging aggregate shares

- draft-irtf-cfrg-vdaf.md
- poc/common.sage
Partially addresses #190.
* Bump version
* Update change log
* Run spellcheck
> draft-05 chores

- draft-irtf-cfrg-vdaf.md
Closes #102.
In general the ability to aggregate a batch multiple times with different aggregation parameters may lead to unintended leakage. We don't really have a great solution for this right now, but point to what we know about this.
> Define the IDPF "prefix tree" and add privacy considerations for it

- draft-irtf-cfrg-vdaf.md
- poc/prg.sage
> Fix a typo

- .github/workflows/test.yml
This installs Sage and runs the test suite. See discussion on #204.
> Run Sage tests in CI

- draft-irtf-cfrg-vdaf.md
> Specify RAND_SIZE for each algorithm

- draft-irtf-cfrg-vdaf.md
- poc/common.py
- poc/idpf_poplar.sage
- poc/prg.sage
- poc/vdaf.py
- poc/vdaf_poplar1.sage
- poc/vdaf_prio3.sage
I also renamed the `DST_...` constants to `USAGE_...` for consistency. Closes #224.
> Rename customization string to domain separation tag

- draft-irtf-cfrg-vdaf.md
- poc/Makefile
- poc/flp.py
- poc/flp_generic.sage
- poc/idpf.py
- poc/idpf_poplar.sage
- poc/vdaf_poplar1.sage
- poc/vdaf_prio3.sage
This converts two more files that are mostly abstract base classes. Part of #204.
> Python conversion: flp.sage and idpf.sage

- poc/daf.py
- poc/field.py
- poc/flp.py
- poc/flp_generic.sage
- poc/idpf.py
- poc/prg.py
- poc/vdaf.py
Stacked on #237
This replaces some custom exceptions with more idiomatic built in exceptions.
> poc: Use built in exceptions

- poc/Makefile
- poc/common.py
- poc/daf.py
- poc/field.py
- poc/flp.py
- poc/flp_generic.sage
- poc/idpf.py
- poc/idpf_poplar.sage
- poc/prg.py
- poc/vdaf.py
> Convert field.sage to Python

- draft-irtf-cfrg-vdaf.md
- poc/Makefile
- poc/flp_generic.py
- poc/vdaf_prio3.sage
This converts flp_generic.sage to Python, as part of #204.
> Convert flp_generic.sage to Python

- draft-irtf-cfrg-vdaf.md
- poc/Makefile
- poc/idpf_poplar.py
- poc/vdaf_poplar1.py
- poc/vdaf_poplar1.sage
- poc/vdaf_prio3.py
This finishes #204 by converting the last three `.sage` files, and cleaning up the Makefile.
> Finish Python conversion

- draft-irtf-cfrg-vdaf.md
Defines three new API calls on `Vdaf` used to describe state transitions while preparing a report.
1. `prep_start()` is a derived method that defines the initial state transition `START` -> `CONTINUED(host_prep_state)`
2. `ping_pong_prep_next()` is a derived method that defines all subsequent state transitions `CONTINUED(host_prep_state)` -> `FINISHED(out_share)` in the "ping pong" flow being discussed for DAP-05 (https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/393).
3. `prep_size()` is a required method that indicates the size of the prep message for a given round. This is needed in order to coalesce prep shares and prep messages into the same, opaque byte string.
This allows us to expose the simplest possible interface to DAP.
> Describe the ping-pong communication pattern used in DAP

- .github/workflows/lint-python.yml
- poc/common.py
- poc/daf.py
- poc/field.py
- poc/flp.py
- poc/flp_generic.py
- poc/idpf.py
- poc/idpf_poplar.py
- poc/prg.py
- poc/vdaf.py
- poc/vdaf_poplar1.py
- poc/vdaf_prio3.py
This formats all the code with autopep8 and isort, and then runs those in a new CI job.
> Format Python code

- draft-irtf-cfrg-vdaf.md
Closes #256.
Say that this is intended to make circuit design more flexible. While at it, give a slightly more realistic example.
cc/ @wangshan
> Clarify the purpose using multiple gadgets (#256)

- draft-irtf-cfrg-vdaf.md
- poc/vdaf.py
- poc/vdaf_poplar1.py
- poc/vdaf_prio3.py
Partially addresses #255.
cc/ @wangshan
> Rename `Vdaf.Prep` to `PrepState` (#255)

- draft-irtf-cfrg-vdaf.md
- poc/vdaf.py
> run_vdaf(): Avoid branching on `Vdaf.ROUNDS` (#223)

- draft-irtf-cfrg-vdaf.md
- poc/prg.py
#209 Switched cSHAKE128 to SHAKE128 in the draft and reference implementation as discussed. The changes here are intended to be minimal, meaning that we pad the domain separation string in the same way that cSHAKE128 pads its customization string, so the only part of the Keccak input that changes is the SHAKE version-identifying postfix. I think a lot of this padding is unnecessary and we can omit it if we like.
> prg: unrolled cSHAKE padding

- draft-irtf-cfrg-vdaf.md
- discovered while reading the draft
> Close code block

- poc/xof.py
> poc: Update rejection test for XofShake128

- poc/plot_prio3_multiproof_robustness.py
> Add a tool for plotting Prio3 robustness bounds

- draft-irtf-cfrg-vdaf.md
> Clarify that public share consistency needn't be explicit

- draft-irtf-cfrg-vdaf.md
- poc/tests/test_idpf_poplar.py
Closes #101.
Big-endian encoding is the most natural choice as it aligns most naturally with our definition of index. We also should note that a reversible padding scheme is needed when the inputs might be variable length.
While at it, pick up a few minor editorial improvements:
- "set of candidate preixes" -> "sequence of candidate prefixes"
- Use one free variable in defining index prefixes
- "Vec" -> "list"
- "Client" -> "Sharding" for consistency with the Prio3 section
> Add guidance for encoding byte strings as IDPF indices

- .github/workflows/test.yml
- poc/vdaf_poplar1.py
- poc/vdaf_prio3.py
> Enforce type hints for vdaf_*.py and all remaining tests

- draft-irtf-cfrg-vdaf.md
- poc/vdaf_poplar1.py
Henry Corrigan-Gibbs suggests the following names:
- "round one" -> "evaluate sketch"
- "round two" -> "reveal sketch"
> Poplar1: Rename preparation steps

- draft-irtf-cfrg-vdaf.md
This closes #364. Stacked on #363.
> Tidy up artwork and sourcecode types

- draft-irtf-cfrg-vdaf.md
> Move mention of {{OriginTelemetry}} and {{ENPA}} to acks

- draft-irtf-cfrg-vdaf.md
- poc/vdaf_poc/common.py
- poc/vdaf_poc/idpf.py
- poc/vdaf_poc/idpf_bbcggi21.py
- poc/vdaf_poc/vdaf.py
- poc/vdaf_poc/vdaf_poplar1.py
- poc/vdaf_poc/vdaf_prio3.py
> Replace `Union[TypeA, TypeB]` with `TypeA | TypeB`

- draft-irtf-cfrg-vdaf.md
> Sketch the star topology for VDAF preparation

- draft-irtf-cfrg-vdaf.md
Closes #257.
Partially addresses #226.
This commit includes editorial improvements for `FlpBBCGGI19`:
1. Add diagrams to show concepts relate to one another: validity circuit, gadgets, encoded measurement, joint, prove, and query randomness, and so on.
2. Improve the overview section, building up each of the concepts one by one.
3. Do an editorial pass of the extensions section, some of which is a little out of date. Also, add a reference for NTT.
> Add diagrams for FLP and rework overview/extensions

- draft-irtf-cfrg-vdaf.md
While at it, re-align some paragraphs.
> idpf: Clarify that the leaf XOF needs to support 16 byte seeds

- draft-irtf-cfrg-vdaf.md
Partially addresses #418.
Note defenses against cross protocol attacks resulting from weak entropy or weak parameters. Also, acknowledge the possibility of cross protocol attacks within a circuit family (no binding of the circuit parameters) and the blast radius of weak parameters (all deployed tasks).
> Add defenses-in-depth section

- draft-irtf-cfrg-vdaf.md
- poc/vdaf_poc/idpf_bbcggi21.py
This fixes a couple long lines introduced in #440.
> Fix long lines

- draft-irtf-cfrg-vdaf.md
Closes #441.
Also, remove its section number.
> Move acknowledgments to last appendix

- draft-irtf-cfrg-vdaf.md
> Add definitions of type hint identifiers

- .github/workflows/archive.yml
- .github/workflows/ghpages.yml
- .github/workflows/lint-python.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- .github/workflows/update.yml
This upgrades various actions we use, to get rid of warnings about Node versions.
> Update GitHub Actions

- draft-irtf-cfrg-vdaf.md
This makes three small, unrelated editorial changes.
> Editorial tweaks

- draft-irtf-cfrg-vdaf.md
> Specify Python minor version

- draft-irtf-cfrg-vdaf.md
* Move Ping-Pong and Start Topologies under Communication Patterns for Preparation
* Move FLP Proof Generation, Query, and Decision out of the Specification subsection. Move the parameter table up to the top of the section and add `valid` to the parameter table.
* Move "Additional Privacy Considerations" for aggregation parameters to the section above.
* Move the limits on IDPF outputs to its own subsection of security considerations.
* Harmonize section titles a little
> Tweak the doc structure

- draft-irtf-cfrg-vdaf.md
> Pass of Poplar1

- draft-irtf-cfrg-vdaf.md
- poc/gen_test_vec.py
- poc/tests/test_daf.py
- poc/tests/test_field.py
- poc/tests/test_flp.py
- poc/tests/test_flp_bbcggi19.py
- poc/tests/test_idpf_bbcggi21.py
- poc/vdaf_poc/field.py
- poc/vdaf_poc/flp_bbcggi19.py
- poc/vdaf_poc/idpf_bbcggi21.py
- poc/vdaf_poc/test_utils.py
- poc/vdaf_poc/vdaf_poplar1.py
> Rename `Field.as_unsigned()` to `int()`

- draft-irtf-cfrg-vdaf.md
> Security considerations: side-channel attacks

- draft-irtf-cfrg-vdaf.md
> Fix typo in references

- draft-irtf-cfrg-vdaf.md
> Update test vectors commit hash

- draft-irtf-cfrg-vdaf.md
This applies a couple more suggestions from #488.
> More updates to common functionalities

- draft-irtf-cfrg-vdaf.md
> Define the method for evaluating a validity circuit

- draft-irtf-cfrg-vdaf.md
> Don't use SHOULD for gadgets being non-affine

- draft-irtf-cfrg-vdaf.md
> Update test vector hash to c0e76dcf8f78d7d36332582f060ab791e5bb1115

- draft-irtf-cfrg-vdaf.md
- poc/tests/test_vdaf_poplar1.py
- poc/vdaf_poc/vdaf_poplar1.py
> Poplar1: Check for trailing bits in agg param

- draft-irtf-cfrg-vdaf.md
Closes #534.
Closes #535.
Closes #540.
> Various changes for draft 15

- draft-irtf-cfrg-vdaf.md
This adds more detail to a couple of paragraphs to address #557.
> Improve description of proof generation, wire seed
