cfrg/draft-irtf-cfrg-vdaf

draft-patton-cfrg-vdaf.md
poc/common.sage
poc/vdaf_prio3.sage

Bind the derivation of field elements to the document name and the
"suite", consisting of the PRG and FLP.

prio3: Add domain separation

---

poc/prg.sage

This fixes a couple hiccups I ran into when running the Sage implementation with some older libraries from my distro. (sagemath 9.0-1ubuntu4 and python3-pycryptodome 3.6.1-2build4) I added a fallback to import PyCryptodome from either of its supported names, and added a conversion from `sage.rings.integer.Integer` to `int` in one place. The second change addresses a ctypes error I got from a PyCryptodome call; presumably newer versions of Sage cooperate with ctypes better on type coercion.

poc: Library compatibility

---

draft-patton-cfrg-vdaf.md

This collects some editorial changes throughout the document.
1. Mention section 7 in the overview
2. Link syntax
3. Stray punctuation
4. "values `beta`" appeared to be a singular/plural disagreement the first time I read it, until later reading that `beta` is itself a pair of values. This change identifies that at its introduction.
5. Wrong variable in pseudocode
6. Further explanation of how the correlation shares could be compressed
7. Typo in pseudocode
8. Copyediting

Editorial changes

---

poc/flp_generic.sage

As far as I can tell this is an unnecessary zip, as `g_calls` is unused in this scope

Remove unused g_calls in FlpGeneric.prove

---

poc/vdaf_prio3.sage

I'm not certain that this is correct, but it seems like `VerifyParam` isn't the `Vdaf` default of `None` for `Prio3`

poc: Add VerifyParam type annotation to Prio3

---

draft-irtf-cfrg-vdaf.md
poc/common.sage
poc/daf.sage
poc/field.sage
poc/flp.sage
poc/flp_generic.sage
poc/prg.sage
poc/vdaf.sage
poc/vdaf_prio3.sage

Backticks get rendered as double quotes in the plaintext version,
potentially colliding with byte string literals in the spec, e.g.:
"b"vdaf-00""
By using single quotes, we ensure this gets rendored instead as
"b'vdaf'00'"
which is a bit clearer.
We may want to consider removing backticks altogether.

editorial: Replace double quotes with single quotes

---

poc/prg.sage

The inputs for this test were chosen through a brute-force search, so that they exercise the rejection sampling logic.
I will be submitting PRs with the same test vector to the Rust and TypeScript implementations.

poc: Add test for expand_into_vec rejection sampling

---

draft-irtf-cfrg-vdaf.md
poc/daf.sage
poc/vdaf.sage
poc/vdaf_prio3.sage

Removes the associated type `AggShare` from `Vdaf` and `Daf` and
modifies the syntax to treat the aggregate share as an opauqe byte
string. This is consistent with input shares, which, like the aggregate
share, are ncessarily transmitted over the network.
This partially addresses #58. In the future we may want to define a type
for every quantity and have that type implement a type whereever
applicable. Or we might decide not to be prescriptive about encoding at
all.
cc/ @tgeoghegan

Specify encoding of aggregate shares

---

draft-irtf-cfrg-vdaf.md
poc/daf.sage
poc/vdaf.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Partially addresses #102.
Each (V)DAF defines a 32-bit codepoint used to uniquely identify it. The
current scheme is as follows:
* The first 3 nibbles are used to identify the VDAF "class", e.g.,
Prio3Aes128 or Poplar1Aes128.
* The remaining 5 nibbles are reserved for particular "instances",
e.g., Prio3Aes128Count, Prio3Aes128Sum, etc.
While at it, incorporate the codepoints into domain separation tags
(DSTs) in Prio3 and Poplar1. This is needed primarily for Prio3. (See
issue#102.)

Define codepoints for (V)DAFs

---

draft-irtf-cfrg-vdaf.md
poc/common.sage
poc/vdaf_prio3.sage

Partially addresses #102.
A bug was found in [BBCGGI+19] that leads to an attack on the robustness
of Prio3. The attack is based on an observation in Appendix A of the
paper "A New Paradigm for Collision-Free Hashing: Incrementality at
Reduced Cost" from Bellare and Micciancio (Eurocrypt 1997). In short,
the attack allows a malicious Client to construct invalid input shares
for which the Aggregators would compute a `k_joint_rand` of its
choosing.
This bug was patched in Section 6.2.3 of
https://eprint.iacr.org/archive/2019/188/20220727:184451 as follows:
Instead of XORing joint randomness shares computed by the
Aggregators, `k_joint_rand` is computed by hashing the shares. This
change patches the Prio3 spec in kind.

Prio3: Align spec with revised paper

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_prio3.sage

Based on #107 (merge that first).
Instead, derive the query randomness from `verify_key` directly.

Prio3: prep_init(): Remove intermediate `k_query_rand`

---

draft-irtf-cfrg-vdaf.md
poc/README.md
poc/vdaf.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Closes #119.
I came across a concern about the robustness of Prio3.The construction uses a PRG to derive joint randomness from the input shares that is used by the client and all aggregators. If a client uploads the same set of input shares twice under distinct nonces, the aggregators will derive the same joint randomness in both preparation phases.Intuitively, this violates the expectation that the joint randomness is pseudorandom, or at least not completely controllable by an attacker. 
More formally, there is a degenerate FLP that is sound  with L bits of security when each set of input shares is submitted at most once, but is vulnerable to an 2^(L/2)-query attack if they can be submitted under many nonces. 
This PR mitigates the attack by including the nonce in the joint randomness …

Add nonces to VDAF sharding syntax & Prio3

---

poc/vdaf.sage

Although large integers are not excluded from the json spec, many languages such as javascript do not correctly parse them into a type that can correctly represent these numbers. This commit changes those large integers into hex strings, as per #116.
Closes #116
Example change to the output json:
```diff
diff --git a/poc/test_vec/03/Prio3Aes128Histogram_0.json b/poc/test_vec/03/Prio3Aes128Histogram_0.json
index f5476455fa53ba563338721391f6f8d15f8c7f46..7bdfc4ef6e54edeed1c595be7cbe926e9cbeea30 100644
--- a/poc/test_vec/03/Prio3Aes128Histogram_0.json
+++ b/poc/test_vec/03/Prio3Aes128Histogram_0.json
@@ -25,16 +25,16 @@
"nonce": "01010101010101010101010101010101",
"out_shares": [
[
-                    316441748434879643753815489063091297628,
- …
```

Fix: Format test vector out shares as hex strings

---

poc/vdaf.sage

This PR updates `TestVdaf` in the proof of concept implementation so that `AggResult` is a bare integer, instead of a vector of integers of length one. At the time this class was written, the aggregate result type wasn't configurable, and this hasn't been updated to take advantage of that yet. This came up during discussion on divviup/divviup-ts#157.

Change TestVdaf.AggResult to Unsigned

---

draft-irtf-cfrg-vdaf.md
poc/idpf_poplar.sage

This updates the IdpfPoplar public share decoding algorithm to check that any unused bits alongside the packed control bits are zero.

Check unused bits when decoding IDPF public share

---

poc/vdaf_prio3.sage

This is thereotically possible now that we don't need this byte for domain separation.
cc/ @hannahdaviscrypto

poc: Prio3: Increase upper bound on share count to 256

---

draft-irtf-cfrg-vdaf.md
poc/common.sage
poc/idpf_poplar.sage
poc/prg.sage
poc/vdaf.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Based on #135 (merge that first).
Closes #106.
Replace `PrgAes128` with a new scheme, `PrgSha3`, that uses SHA-3 in the cSHAKE128 mode of operation. Existing analysis models this object as a random oracle, and SHA-3 is a safer way to instantiate it.
Whenever the PRG is used to map a seed and some context to a finite domain, e.g., derive a fresh seed or a vector of field elements, the analysis models this function as an independent random oracle. One consequence of this is that we need to take care to ensure domain separation for each distinct usage of PRG. In particular, we need to format the inputs to the random oracle so that they are decodable.
To make this easier, we split the current "info string" into two components: The "context string" and the "binder string". The context string …

Use SHA-3 to instantiate the PRG and improve domain separation

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.sage

Based on #136 (merge that first).
Use a different `Prg` instance for the inner and leaf nodes when generating shares of the offsets for the sketch computation (i.e., the `(a, b, c)` triples). This change is meant to reduce implementation complexity. In particular, for performance reasons it is desirable to buffer the seed stream output by the `Prg` prior to doing rejection sampling. The buffer size is picked based the size of the field elements; changing the field size is fiddly, as this requires us to copy the unused part of the buffer to the beginning when we wrap around the end. For details, see:
https://github.com/divviup/libprio-rs/pull/429

Poplar1: Split PRG for leaf/inner sketch offsets

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.sage

Based on #137 (merge that first).
Security requirements will require us to restrict preparation so that the sketch computed only once per level of the IDPF tree. Remove the prefixes from the verifier randomness derivation, as this will not be needed.

Poplar1: Don't derive verifier randomness from prefixes

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.sage

Based on #138 (merge that first).
If the candidate prefixes are not unique, then the refined measurement may not be a one-hot vector. This would cause the Aggregators to fail sketch verification when it would have otherwise passed.

Poplar1: Enforce prefix uniqueness

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.sage

Based on #139 (merge that first).
Use 32 bits to encode the number of prefixes rather than 16. We don't want 2^16-1 to be a hard limit.
While at it, add some roundtrip tests for aggregation parameter serialization.

Poplar1: Increase candidate prefix count encoding

---

poc/prg.sage

This adds an additional test of the rejection sampling behavior, using `PrgSha3` instead of `PrgAes128`.

Add rejection sampling test for PrgSha3

---

draft-irtf-cfrg-vdaf.md
poc/idpf_poplar.sage

This changes the byte order of the packed control bits in the IdpfPoplar public share. The order of bits within each byte is the same, but control bits for the first level will now be encoded in the first byte of the public share.
Closes #147.

IDPF: Change byte order of packed control bits

---

poc/prg.sage

fyi/ @simon-friedberger: @divergentdave thought it would be sensible to add a length prefix to the customization string.

poc: Ensure the customizer for PrgAes128 is decoable

---

draft-irtf-cfrg-vdaf.md

Set `NONCE_SIZE` in the Prio3 and Poplar1 constructions, as required by the VDAF definition. The nonces are 16 bytes long, matching the existing Sage reference implementations.
Related to #127

Specify nonce sizes for Prio3 and Poplar1

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.sage

This hoists the final sketch verification check from `prep_next()` to `prep_shares_to_prep()`. As a result, the round 2 prepare message will always be the empty string, if it doesn't raise an error. (Previously, it could have been the empty string or a 32-byte encoded field element)
Closes #169.

Poplar1: Hoist sketch check to prep_shares_to_prep

---

draft-irtf-cfrg-vdaf.md
poc/common.sage
poc/field.sage
poc/idpf_poplar.sage
poc/prg.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Closes #90 
Add methods to_le_bytes/from_le_bytes for encoding/decoding unsigned
integers as little-endian bytes and use these for field element
serialization. This change is meant to improve alignment of the spec
with implementations, which largely prefer little endian to big endian
for representing field elements.
For consistency, rename I2OSP/OS2IP to to_be_bytes/from_be_bytes.
While at it, check in David's script for generating the PRG rejection
test case. This is not strictly needed, since we could just reverse the
order of the bytes in the test seed, but it will be useful later on.

Use littlen-endian byte-order for fields

---

poc/prg.sage

This changes out the rejection sampling test to use Field64, which is actually in the document. There's less of a gap between the Field64 modulus and the largest 64-bit integer than in the Field96 case, so I wrote a small Rust program to do so, instead of using Python. (the search takes about ~30s on eight cores with this, it was too slow with Python) For what it's worth, finding similar test vectors for Field128 and Field255/GF(2^255-19) is infeasible to practically impossible.

Change rejection sampling test to use Field64

---

poc/flp_generic.sage
poc/idpf_poplar.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Partially addresses #163.
Properly construct a subclass instead of attempting to deep copy the superclass. The old pattern did not have the intended effect, which results in some subtle bugs.

poc: Replace "deepcopy" pattern for class factories

---

poc/common.sage
poc/daf.sage
poc/idpf.sage
poc/idpf_poplar.sage
poc/vdaf.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Based on #184 (merge that first).
Partially addresses #173.
To improve test vector quality, we will need to be able to specify a particular sequence of random coins used by the Client to split its measurement.
Add a paramter to `Daf.measurmeent_to_input_shares()` and `Vdaf.measurmeent_to_input_shares()` for the random coins. In addition, have the object specify the size of the byte string it expects. Similarly for `Idpf`.
Accordingly, remove all calls to `gen_rand()` from `Prio3`, `Poplar1`, and `IdpfPoplar` and instead use the coins passed to the API.

poc: Plumb coins to `measurement_to_input_shares()`

---

poc/idpf.sage
poc/idpf_poplar.sage
poc/prg.sage
poc/vdaf.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Based on #187 (merge that first).
Partially addresses #173.
We currently use the class name to name the file containing teste vectors for it. We create subclasses to specialize a `Vdaf` (or `Prg`, `Idpf`, etc.) with a given parameter. It is helpful to have that subclass have a distinguished name, e.g., `Prio3SumWithShares`. However, this name is not particularly helpful as a name for the file.
To fix this, add a `test_vec_name` class parameter to each class for which we generate test vectors and use that as the filename instead of `__class__`.

poc: Don't use class name for test vector name

---

draft-irtf-cfrg-vdaf.md
poc/daf.sage

Closes #173.
* Add a parameter to all randomized algorithms that consists of the random coins consumed by that algorithm. Namely:
* `Daf.measurement_to_input_shares()`
* `Vdaf.measurement_to_input_shares()`
* `Idpf.gen()`
Have the algorithm specify the required length of the random istring.
* Update `Prio3`, `Poplar1`, and `IdpfPoplar` accordingly.
* Update `run_daf()` and `run_vdaf()` accordingly.
* Revise description of fixed random coins used for generating test vectors.
While at it, pick up a couple small editorial things:
* Replace instances of "input-distribution algorithm" with "sharding algorithm" for consistency.
* poc: Fix typo in a comment in `run_daf()`.

Propagate changes to randomness handling to spec

---

poc/vdaf.sage

There's a stray big-endian encoding of field elements in the test vector formatting code, this PR fixes it and brings it in line with how the other fields are encoded.

Fix encoding of output shares in test vectors

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_prio3.sage

This PR rearranges the order in which Prio3 is defined to take seeds for various purposes from its random input string. This will change test vector output. This change is intended to simplify implementation in libprio-rs, see divviup/libprio-rs#499 for prior discussion. The key changes are that a) helper measurement shares and proof shares are interleaved, b) helper joint randomness blinds are also interleaved after other per-helper seeds, if present, (both to keep related seeds near each other) c) the leader joint randomness blind comes after all helper-related seeds (since it will naturally be used last, as its measurement share must be computed last), d) the proof randomness seed is taken from the last seed in the random input. (since it's used last)
As a nice side benefit, the …

Prio3: Change order of seeds in random coins

---

draft-irtf-cfrg-vdaf.md
poc/idpf.sage
poc/idpf_poplar.sage
poc/prg.sage
poc/vdaf_poplar1.sage

Add fixed-key AES specification

---

poc/idpf.sage

This adds the binder input to the IDPF test vector, since it's now an input to the key generation function.

Include binder in IDPF test vector

---

draft-irtf-cfrg-vdaf.md

* Make the stuff about the IDPF prefix tree leakage a subsection of the aggregation parameter section
* Capitalize "Random Oracle" in the section title

editorial: Fix up sections in Security Considerations

---

.gitignore
poc/Makefile
poc/README.md
poc/common.py
poc/daf.sage
poc/field.sage
poc/flp.sage
poc/flp_generic.sage
poc/idpf.sage
poc/idpf_poplar.sage
poc/prg.sage
poc/vdaf.sage
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

This converts `common.sage` to Python, as a first incremental step towards #204. This required two `^` changes, and then adjustments to import statements in other files.

Convert common.sage to Python

---

poc/common.py

This changes the superclass of `Error` to be `Exception` instead of `BaseException`. The [exception documentation](https://docs.python.org/3/library/exceptions.html) says that new exception types should typically do so. Inheriting directly from `BaseException` is reserved for special things like `GeneratorExit`, `KeyboardInterrupt`, `SystemExit`, etc.

poc: Change superclass of Error to Exception

---

poc/common.py

This simplifies `print_wrapped_line()`: we don't need to use `min()` because string slicing in Python automatically truncates.

Simplify print_wrapped_line()

---

poc/common.py

This moves comments describing methods into docstrings, so they'll appear in IDEs, etc.

common.py: Move comments to docstrings

---

draft-irtf-cfrg-vdaf.md
poc/Makefile
poc/daf.py
poc/daf.sage
poc/vdaf.py
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

This is part of #204. These two modules are mostly abstract base classes, so this conversion was straightforward.

Convert daf and vdaf modules to python

---

draft-irtf-cfrg-vdaf.md
poc/flp.sage
poc/flp_generic.sage

This improves `run_flp()` to actually split the input and proof into shares, query each, and reassemble the verifier before running the decision algorithm.
Fixes #227.

Split up inputs and proofs in run_flp()

---

poc/Makefile
poc/daf.py
poc/idpf.py
poc/idpf_poplar.sage
poc/prg.py
poc/vdaf.py
poc/vdaf_poplar1.sage
poc/vdaf_prio3.sage

Part of #204. I replaced divisions that resulted in Sage rational numbers followed by `int()` casts with `__floordiv__` division. An int cast is needed when using `Field.ENCODED_SIZE`, as that's still a Sage integer for the time being, and some Pycryptodome methods using FFI calls are not tolerant of Sage integers.

Convert prg.sage to Python

---

draft-irtf-cfrg-vdaf.md
poc/flp_generic.py
poc/vdaf_prio3.py

This changes Prio3Histogram so that it is parameterized by a number of buckets, instead of a list of bucket boundaries. The measurement is now an index into the buckets, instead of an integer that's compared with the bucket boundaries. Closes #239. I confirmed that the messages in the Prio3Histogram test vector data are unchanged. (the parameter and measurement naturally changed)

Redefine Prio3Histogram measurement and parameters

---

poc/vdaf.py
poc/vdaf_prio3.py

This PR adds code to generate Prio3 test vectors with three shares. I also added the number of shares to the test vector itself, because I figure it's easier to do so here than for consumers to count aggregate shares or input shares. Closes #245.

Generate Prio3 test vectors with three shares

---

poc/vdaf.py

This adds the `rand` input to the machine-readable JSON test vectors, so that consumers don't have to implement its generation. This also opens the door to making randomness used in test vectors even more interesting. Closes #246.

Add "rand" input to test vectors

---

draft-irtf-cfrg-vdaf.md
poc/daf.py
poc/vdaf.py
poc/vdaf_poplar1.py
poc/vdaf_prio3.py

Closes #260.
Rename:
* measurement_to_input_shares -> shard
* out_shares_to_agg_share -> aggregate
* agg_shares_to_result -> unshard

Use verbs for API calls (#260)

---

draft-irtf-cfrg-vdaf.md
poc/flp.py
poc/flp_generic.py
poc/vdaf_prio3.py

This makes a variety of changes to the FlpGeneric implementation to simplify things and better follow Python conventions, and then replaces the existing gadget/circuit pseudocode in the document with extracts of the corresponding `eval()` methods. The biggest change is that all the Flp and Valid APIs that were in class methods were moved to plain methods, and the subclass factories were replaced with plain constructors. I renamed several arguments to either avoid upper-case names or shadowing of bindings from outer scopes. (I left `Field` as-is for now, since we also import a module named `field`) I also defined a `Range2` gadget, effectively a specialization of `PolyEval`, so that we can use it in the validity circuits that already claim to use it, and I can extract its `eval()` method …

Clean up Gadget, Valid, and Flp APIs, update extracts in document

---

draft-irtf-cfrg-vdaf.md
poc/flp.py
poc/flp_generic.py
poc/vdaf.py
poc/vdaf_poplar1.py
poc/vdaf_prio3.py

This introduces the ParallelSum gadget and uses it in Prio3SumVec, which computes sums of vectors of integers.
This differs from the `Prio3SumVec` implementation that's been in libprio-rs for a while in three respects. First, the chunk length is now an explicit parameter, rather than being floor(sqrt(length * bits)). This both lets us dodge compatibility concerns about how exactly to compute that square root, and provides flexibility to squeeze a few more bytes out by using more optimal chunk length choices. (There are two different kinds of rounding involved in the proof size formula, plus there's a factor of two in front of the rounded number of calls) Second, libprio-rs defined a `BlindPolyEval(x, r) = r * p(x)` gadget for use in this validity circuit, but this PR just uses `Mul(x, y) …

Add Prio3SumVec

---

draft-irtf-cfrg-vdaf.md
poc/flp_generic.py
poc/vdaf_prio3.py

This implements #274, hoisting the description of the ParallelSum gadget up a section, and changing the Histogram circuit to use it as well. This reduces report sizes by a bit under two thirds asymptotically. Sharding performance is improved for large histograms as well (I got 27% reduction in runtime for a length of 1000)

Apply parallel sum optimization to Histogram FLP

---

draft-irtf-cfrg-vdaf.md

This is a follow-up related to #124, explaining why optimal chunk lengths are not easy to find, and providing some more context about how good the square root rule of thumb/RECOMMENDation is.

Expand upon chunk length selection

---

draft-irtf-cfrg-vdaf.md

A handful of fixes to the specification of the ping-pong aggregator
communication topology encountered during implementation.
- Explicitly describe Python objects for ping-pong State
- `ping_pong_leader_init` and `_helper_init` return `Message`, not `bytes`
- `ping_pong_transition` always returns a `Message`
- typo in `ping_pong_transition`
- `ping_pong_continued` fails if `state` is not `Continued`
- remove unused `is_leader` parameter from `ping_pong_transition`

Ping-pong topology fixes

---

poc/flp_generic.py

__name__ is an attribute of a class instead of that of an instance. flp.Valid is an instance, so accessing __name__ will fail with another exception if the FLP test fails.

Fix __name__ access in poc

---

poc/flp_generic.py
poc/vdaf_prio3.py

1. POC implementation for mutliproof proposal in  [#177](https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/177)
1. Support multiproofs in `Prio3`
2. Add new `Prio3SumVec` variant, i.e. `Prio3SumVecWithMultiproof`, with configuration (field size, number of proofs)
3. Add `with_field` class methods to introduce new `SumVec` with configurable field size

Add poc changes for [#177]

---

poc/flp_generic.py
poc/vdaf_prio3.py

Add a reference implementation of the idea in issue #287, which needs a new FLP 'MultiHotHistogram' and a new Prio3 type 'Prio3MultiHotHistogram' that checks a Client's measurement has a bounded number of 1s.

Implement Prio3MultiHotHistogram that checks bounded number of 1s

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.py

Also use the nonce for the sharding XOF in poplar1, and make the poplar1 pseudocode in the spec consistent with the reference implementation.

Add language about how the binder string / nonce is used in Poplar1

---

draft-irtf-cfrg-vdaf.md

Closes #307. I noticed the following error messages when running `make`:
```
*** attributes left {"authors"=>[{"ins"=>"C. Guo"}, {"ins"=>"J. Katz"}, {"ins"=>"X. Wang"}, {"ins"=>"C. Weng"}, {"ins"=>"Y. Yu"}]}!
*** attributes left {"authors"=>[{"ins"=>"C. Guo"}, {"ins"=>"J. Katz"}, {"ins"=>"X. Wang"}, {"ins"=>"Y. Yu"}]}!
```

Fix metadata of informative references

---

.github/workflows/test.yml
.gitmodules
draft-irtf-cfrg-vdaf.md
poc/daf.py
poc/vdaf_poplar1.py
poc/vdaf_prio3.py
poc/xof.py

Closes #299.
The reference code uses the reference implementation of TurboSHAKE128. This code is unoptimized, so care is needed to ensure our tests run in a reasonable amount of time.
Each time `XofTurboShake128` is constructed we call `TurboSHAKE128()` once and fill a buffer with the output stream. The size of the buffer is a constant, `MAX_XOF_OUT_STREAM_BYTES`, chosen to be sufficiently long for every test that we have. So that we don't have to make this value too large, some of tests in `vdaf_poplar1.py` have been modified.

Replace SHAKE128 with TurboSHAKE128

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_prio3.py

Partially addresses #177.
The query randomness is correlated for different values of `Prio3.PROOFS`. To provide defense in depth in case the same verification key is used for different versions, prepend the binder with `bytes(Prio3.PROOFS)`.
For consistency, do the same for the prove randomness and each Helper's share of the proofs. Also, do the same for joint randomness in case `Prio3.PROOFS == 1`.

Prio3: Improve domain separation for multi-proof mode

---

poc/xof.py

This will resolve two problems:
- When another repo tries to submodule this repo, we won't hit problems when trying to import kangerootwelve
- We don't always have to run unit tests from the "poc" folder, e.g., I can still run unit tests from the root directory of this repo, sage -python poc/vdaf_prio3.py

Infer relative path of kangerootwelve

---

poc/Makefile
poc/turboshake.py
poc/vdaf_poplar1.py
poc/xof.py

Closes #321.
The reference implementation of TurboSHAKE128 provides a one-shot API. To use this efficiently, we restrict the number of bytes required for tests so that we can pre-compute the entire output buffer. This is controlled by MAX_XOF_OUT_STREAM_BYTES.
This restriction is confusing and has side-effects for specs that use XofTurboShake128. However using the one-shot API without this optimization makes the unit tests prohibitively slow, about a minute on my machine.
Implement a stateful API for TurboSHAKE128 and use it in XofTurboShake128. This reduces the runtime to 20 seconds on my machine.
Accordingly, restore the unit tests for Poplar1 to what they were before we made this optimization.
cc/ @junyechen1996

poc: Reduce test runtime by making TurboSHAKE128 stateful

---

poc/README.md
poc/common.py
poc/idpf.py
poc/vdaf.py
poc/xof.py

Add an environmental variable TEST_VECTOR to control test vector generation, and an optional environmental variable TEST_VECTOR_PATH to specify a custom path where test vectors are generated. Add a new target in Makefile to generate all test vectors in VDAF spec.

Improvements to test vector generation

---

draft-irtf-cfrg-vdaf.md

Closes #311.
For Prio3, when joint randomness is used:
* RECOMMEND Field128
* Field64 MAY be used, but `PROOFS` MUST be `3`
The latter is motivated by issue #177. The recommendation is based on the upper bound given by {{DPRS23}}, Theorem 1 and a matching attack described by @bwesterb (see issue #311).

Add guidance for choosing the field size

---

draft-irtf-cfrg-vdaf.md

Closes #42.
We had considered whether we could bake the idea of a "linear state machine" into the VDAF syntax. We could probably do something here, but our best idea involves mucking with type hints, something that has created some code rot in this repository already. Since no one has complained about this, let's just rule it out. Also, note that if we end up simplifying the syntax to only supporting 1-round VDAFs, then this point will be moot.
Also, we had a paragraph about 0-round VDAFs, which our syntax currently rules out. Delete the paragraph and the associated OPEN ISSUE.

Rule out some ideas for streamlining preparation syntax

---

draft-irtf-cfrg-vdaf.md

Closes #94.
As written, the intro seems to frame MPC as an alternative to DP, which is not true. Rather, we want to frame MPC as a necessary component of a data aggregation system that provides DP.
~Indeed, this change goes a step forward: VDAFs SHOULD be composed with a mechanism for DP.~

Clarify that VDAFs aren't sufficient for DP

---

draft-irtf-cfrg-vdaf.md
poc/common.py
poc/field.py
poc/flp_generic.py
poc/idpf_poplar.py
poc/tests/test_flp.py
poc/tests/test_flp_generic.py
poc/vdaf_poplar1.py
poc/vdaf_prio3.py

Based on #350 (merge that first).
Closes #277.
Use a generic Python exception with a helpful error message. `ValueError` is the natural choice for all of our cases.

Replace generic `ERR_*` exceptions

---

.github/workflows/test.yml
draft-irtf-cfrg-vdaf.md
poc/field.py
poc/xof.py

Partially addresses #59.
Add type hint enforcement with mypy to CI, starting with field.py and xof.py. This checks that the variables passed into a function match the function's type hints.

Enforce type hints in field.py, xof.py

---

draft-irtf-cfrg-vdaf.md

Closes #304.
Add the following clarifications to our thread model:
- Privacy assumes the attacker does not control transmission of messages between the honest Clients and Aggregators.
- Robustness assumes the attacker eavesdrops on the network but does not control transmission.
This implies that guaranteed output delivery and malicious robustness are not guaranteed.

Clarify network assumptions and limits on robustness

---

.github/workflows/test.yml
poc/flp.py
poc/flp_generic.py

Partially addresses #59.
The "associated type" pattern we're trying to follow is not enforceable.
For example, we'll do something like this:
```
class Foo:
Measurement = None
def bar(self, m: Measurement): pass
```
`mypy` complains because `None` is not a valid type. We instead could do
the following:
```
class Foo:
Measurement: Any = None
def bar(self, m: Measurement): pass
```
A concrete sub-class would override this in the natural way:
```
class FooForInt(Foo):
Measurement = int
def bar(self, m: int): pass
Foo().bar(23)
Foo().bar("23")
FooForInt().bar(23)
FooForInt().bar("23") # fails
```

Enforce type hints for flp.py, flp_generic.py, and tests

---

draft-irtf-cfrg-vdaf.md
poc/flp_generic.py
poc/tests/test_flp_generic.py
poc/tests/test_vdaf_prio3.py
poc/vdaf_prio3.py

Closes #287.
Assign Prio3MultiHotHistogram a codepoint (0x00000004) and add it to the draft under the name Prio3MultihotCountVec. Also, rename "count" to "weight", as in the "weight of the vector" (i.e., the number of non-zero entries).

Add Prio3MultihotCountVec to the draft

---

draft-irtf-cfrg-vdaf.md
poc/flp_generic.py
poc/tests/test_flp_generic.py

Closes #262.
Partially addresses #306.
If the input is valid, then each output should be zero. To save bandwidth, we generate an extra element of query randomness and use it to reduce the result.
To exercise this feature, implement a new circuit, `Sum2`, that generalizes `Sum` to support any bound, including non-powers-of-two.

flp: Make the output of `Valid` a vector

---

draft-irtf-cfrg-vdaf.md
poc/common.py

This adds some missing checks that vectors are of the same length in `vec_add()` and `vec_sub()`. The prose introducing these claims that "an exception is raised by each function if the operands are not the same length", but that wasn't true yet. `zip()` stops yielding when any input iterator does, so we need to explicitly check for this case.
```python
>>> list(zip([1], ['a', 'b']))
[(1, 'a')]
```

Check vector lengths when adding/subtracting

---

draft-irtf-cfrg-vdaf.md

This sets the submission type to IRTF. See https://datatracker.ietf.org/doc/html/rfc7991#appendix-A.2 for its definition. Note that `kramdown-rfc2629` supports this as one of three [aliases](https://github.com/cabo/kramdown-rfc/blob/6aef289cc6f39e1c851f92efbc69c4ac917c0537/data/kramdown-rfc2629.erb#L32) to set the `submissionType` attribute on the `<rfc>` tag. This clears up the following warning:
> Warning: Expected a valid submissionType (stream) setting, one of IETF, IAB, IRTF, independent, editorial, but found None.  Will use 'IETF'

Set submission type to IRTF

---

draft-irtf-cfrg-vdaf.md

This text is superseded by the last paragraph of {{sec-vdaf-prepare}}, which says,
> The preparation-state update accomplishes two tasks: recovery of output shares
> from the input shares and ensuring that the recovered output shares are valid.
> The abstraction boundary is drawn so that an Aggregator only recovers an output
> share if it is deemed valid (at least, based on the Aggregator's view of the
> protocol). Another way to draw this boundary would be to have the Aggregators
> recover output shares first, then verify that they are valid. However, this
> would allow the possibility of misusing the API by, say, aggregating an invalid
> output share. Moreover, in protocols like Prio+ {{AGJOP21}} based on oblivious
> transfer, it is necessary for the Aggregators to interact in order to …

Remove HTML comment about Prio+

---

draft-irtf-cfrg-vdaf.md
poc/xof.py

This wraps the remaining long lines in the document that were causing warnings.

Fix remaining line length warnings

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poplar1.py

Closes #366.
The prep message type for Poplar1 is `Optional[FieldVec]`. The `None` variant is intended to be used in place of `[field(0)]`. This is the message we expect on the second round when the input is valid, so this saves a little bit of bandwidth.
We also use it in place of the length-3 vector of zeros. That is, if an Aggregator gets `None` in the first round, it will replace the message with `[field(0)] * 3` and proceed as if this is the message it received. However, in an honest execution of the protocol, the Aggregator will never receive `None` in the first round.
This commit modifies the behavior of `prep_next()` by treating this explicitly as an error. This change doesn't seem strictly necessary, as the all-zero vector is likely to be rejected, and in any case an attacker can …

Poplar1: On first prep round, handle none as error

---

draft-irtf-cfrg-vdaf.md

Using square brackets around these notes causes Markdown issues. Rather than try to escape the brackets, I decided to use parentheses instead, because a quick Google search suggests parentheses are more common for these sorts of remarks.

Use parentheses around notes to RFC editor

---

draft-irtf-cfrg-vdaf.md

`Sum` was copied into the `SumVec`, `Histogram`, and `MulithotCountVec` sections.

Fix copy-pasta in Prio3 variant tables

---

draft-irtf-cfrg-vdaf.md
poc/daf.py
poc/tests/test_daf.py

This PR updates `is_valid()` for DAFs to take a list of previous aggregation parameters, following a similar change to VDAFs. It also updates the description of VDAF sharding to reflect that DAF sharding has the same sets of inputs and outputs.

Sync up descriptions of DAFs and VDAFs

---

draft-irtf-cfrg-vdaf.md

Closes #380.
It may be desirable to store the measurement share seed rather than the output share.

Prio3: Add an implementation note about the output share

---

draft-irtf-cfrg-vdaf.md

Closes #219.
Closes #346 (the new intro rework leans into DAF being a core part of the draft).
* Introduce DAFs first, in order to mirror the document structure.
* Explain (function) secret sharing and give examples of aggregation functions that can be computed with (V)DAFs
* Give less detail about Prio3 and Poplar1
* Point to discussion about non-collusion in {{overview}}
Also, in security considerations, discuss dealing with non-static corruptions and how to pick the number of aggregators. This addresses an idea for the intro, but resolving it seems to require a proper security consideration.

Address feedback on the intro

---

draft-irtf-cfrg-vdaf.md

These arrows are important for the diagram because they have implications for how you architect a protocol around a VDAF.
fyi/ @bhalleycf

Add prep state to prep diagram

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_vdaf_ping_pong.py
poc/vdaf_poc/vdaf_ping_pong.py

Closes #283.
Based on #386 (merge that first).
Add an implementation of the ping-pong API to the reference code. The
pseudocode currently in the draft doesn't compile, so replace it with
the tested, type-checked, and linted Python.
Also, in the draft, we don't need to list the encoding methods used by
the ping-pong API; these should be clear in context.

Replace pseudocode for ping-pong topology with Python

---

poc/gen_test_vec.py
poc/vdaf_poc/test_utils.py

This makes it easier for other projects to generate VDAF test vectors with the same format.

Move test vector generator to test utils

---

.github/workflows/archive.yml
.github/workflows/ghpages.yml
.github/workflows/publish.yml

v2 has been deprecated for some time:
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Bump update-artifact to v4

---

draft-irtf-cfrg-vdaf.md

This PR replaces the IANA considerations with a more IETF/IRTF-standard formulation.  It provides precise instructions to IANA as to how to construct and manage the registry.
This PR also adds some discussion about how these identifiers are used, to guide applications toward VDAF IDs that are less likely to accidentally collide.
Fixes #110

Flesh out IANA considerations

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_field.py
poc/vdaf_poc/field.py
poc/vdaf_poc/idpf_bbcggi21.py

This simplifies some code in `gen()` and `eval_next()` by using control flow instead of multiplications and conditional selects. I added and updated implementation notes about timing side channels.

IDPF: Simplify code, add constant-time notes

---

draft-irtf-cfrg-vdaf.md
poc/plot_prio3_multiproof_robustness.py

The security consideration section has the following recommendation for choosing parameters for circuits with joint randomness: "Field128 is RECOMMENDED, but Field64 MAY be used with at least three proofs".
Clarify where this requirement comes from (the base proof system needs around 128 bits of security) and strengthen this language somewhat: "Either Field128 or Field64 with three proofs MUST be used".
This change was suggested in an offline conversation with @henrycg.

Strengthen recommendation about field size

---

.github/workflows/lint.yml
draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/flp_bbcggi19.py

This fixes another long line, introduced in a recent PR. It also adds a check to CI to catch such warnings going forward.
I tested that this works in CI, see https://github.com/cfrg/draft-irtf-cfrg-vdaf/actions/runs/11220047961/job/31187354251.

Fix long line

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/vdaf_poplar1.py
poc/vdaf_poc/vdaf_prio3.py

Closes #435.
Also, add a `_seed` suffix where the new variable name is confusing: `k_prove` -> `prove_seed` in Prio3; and `k_shard` -> `shard_seed` in Poplar1.

Remove `k_` prefix from seed variables

---

draft-irtf-cfrg-vdaf.md

Closes #439.
RFC 9180 (HPKE) and has an informative reference to draft-ietf-tls-esni (a protocol that uses HPKE). It's therefore reasonable to believe that VDAF may have an informative reference to draft-ietf-ppm-dap.

Remove RFC EDITOR note about DAP draft

---

.github/workflows/lint.yml

This improves the new step in the "Lint document" job by failing on errors as well (via `-o pipefail`) and passing through error messages. This is largely handled by the "Update Editor's Copy" job, but it makes sense that this job should fail as well.
Testing:
- With a warning: https://github.com/cfrg/draft-irtf-cfrg-vdaf/actions/runs/11240619833/job/31250344834
- With an error: https://github.com/cfrg/draft-irtf-cfrg-vdaf/actions/runs/11240640344/job/31250406562

Pass through errors in addition to warnings

---

poc/gen_test_vec.py
test_vec/vdaf/Poplar1_4.json
test_vec/vdaf/Poplar1_5.json

This adds two additional Poplar1 test vectors, with `BITS=11`. One evaluates the first level, and the other evaluates the last level. This addition will flush out possible issues with byte order in the IDPF public share's control bit correction words. (the existing test vectors are all for `BITS=4`)

Add two more Poplar1 test vectors

---

draft-irtf-cfrg-vdaf.md

Closes #312.
Set the commit hash to 1891650bb8d23eb82663a0c05a5e37e97c4b5a96.
We may of course end up changing or adding more test vectors in the future, in which case we'll need to update the commit hash once more.

Finalize commit hash for test vector reference

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_daf.py
poc/tests/test_vdaf_ping_pong.py
poc/vdaf_poc/daf.py
poc/vdaf_poc/test_utils.py
poc/vdaf_poc/vdaf.py
poc/vdaf_poc/vdaf_poplar1.py
poc/vdaf_poc/vdaf_prio3.py

Closes #432.
Modify both `Daf` and `Vdaf` by replacing `aggregate()` with two
methods:
* `agg_init()` returns an empty aggregate share
* `agg_update()` updates an aggregate share with an output share
Also, add a method `merge()` for merging two aggregate shares, as will be required for specifying aggregation in DAP.

Replace `aggregate()` with streaming API

---

draft-irtf-cfrg-vdaf.md

* Add ticks around constants in-lined in a paragraph.
* Replace explanation of domain separation with reference to the defense-in-depth section.

Spot check IANA Considerations

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_flp_bbcggi19.py
poc/vdaf_poc/field.py
poc/vdaf_poc/flp_bbcggi19.py

Stacked on #449 (to reduce rebase conflicts later on).
Closes #411.
Rework the spec of each Prio3 variant by listing the entire class of each circuit. Also, list the specification of each gadget in 
the appendix.
* Prio3Sum: Use `PolyEval` instead of `Range2`, as this is a much more useful gadget to list in the doc.
* Say "variant" instead of "instance".
* Document missing operations on polynomials
* Modify the constructor for `Field` elements by interpreting negative integers as additive inverses. This is necessary in  order to allow expressing polynomial coefficients in the `PolyEval` circuit independent of the field modulus.

Prio3: Improve circuit specifications

---

draft-irtf-cfrg-vdaf.md

This deletes a number of duplicate word typos, and rephrases two sentences to make more sense in plain text (where the inline code formatting does not appear).

Fix duplicate words

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/xof.py

Stacked on #475.
Previously we imagined making this generic in case we wanted to define variants with different XOFs. We don't have nay in this document, so fix XofTurboShake128 as the XOF as early as possible.
While at it, don't overload `Xof` in parameter tables, as this is now just an abstract base class. Likewise for `Idpf` and `Flp`.

Prio3, Poplar1: Set `xof` to `XofTurboShake128`

---

draft-irtf-cfrg-vdaf.md

This fixes #480 by tweaking the table to say `Count(field)`, etc.

Fix duplication of field in Prio3 variant params

---

.github/workflows/lint-python.yml
draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/vdaf_ping_pong.py

Pass of VDAF prep communication patterns

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/common.py
poc/vdaf_poc/field.py
poc/vdaf_poc/xof.py

Stacked on #483.
* Note that `Field.rand_vec()` is not used in the spec of any VDAF. (It's only used for `run_flp()`.)
* Specify notation of arithmetic operations on fields.
* Use `front()` in field element decoding, which is more in line with how we write down decoding algorithms in other parts of the draft.
* Say what we mean by "order" of the multiplicative subgroup of NTT fields
* XofTurboShake128: Set stricter bounds on the inputs (how big can the seed be)
* XofFixedKeyAes128: Set bounds on the length of the domain separation tag.
* Clarify the motivation for XofFixedKeyAes128.
* Write "AES128" instead of "AES-128" as this is how we denote the function in the spec.

Pass of preliminaries

---

draft-irtf-cfrg-vdaf.md

Stacked on #489.
* Harmonize conventions for naming conferences
* seriesinfo == name of the conference (with common acronym in
parantheses) w/o the edition (this is the same as the year)
* Remove some redundant text about the security model of {{DPRS23}}.
* Say applications SHOULD bind the verification key to the context
* Define "steering attack" (this name should be handy later on)

Pass of security, references, appendices, and acks

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_field.py
poc/vdaf_poc/daf.py
poc/vdaf_poc/field.py
poc/vdaf_poc/flp_bbcggi19.py
poc/vdaf_poc/vdaf.py
poc/vdaf_poc/vdaf_prio3.py

Stacked on #498.
Miscellaneous improvements:
* Add an illustration of DAF preparation
* Clean up bounds on `run_daf()` and `run_vdaf()`
* Document only the pre-conditions that are relevant
* Remove code for enforcing the pre-conditions
* Use comments only for the stages of execution: sharding, preparation, etc.
* Punt VDAF prep state listing to appendix
* Rename `encode_to_bit_vector()` to `encode_to_bit_vec()` for consistency with abbreviation of "vector" to "vec" in other functions
* In titles, rename "Construction" to "Specification"
* In Prio3, list `prep_shares_to_prep()` before `prep_next()` so that the computations are listed in chronological order. (We could do the same for Poplar1, but there it's less helpful because we end up calling `prep_next()` twice.)

Clean up after full pass

---

poc/vdaf_poc/daf.py
poc/vdaf_poc/vdaf.py

Add a common base class to Daf and Vdaf

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_daf.py
poc/vdaf_poc/daf.py
poc/vdaf_poc/test_utils.py
poc/vdaf_poc/vdaf.py

Remove nonces from `run_daf()` and `run_vdaf()`

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_field.py
poc/vdaf_poc/field.py
poc/vdaf_poc/idpf_bbcggi21.py

Closes #496.
Use `bool` for the IDPF control bits instead. `Field2` was relevant when we were implementing control bit masking in an earlier version of the draft, but now that we're leaving side channel considerations completely to the implementer (for readability's sake), `bool` is a little cleaner.

Remove `Field2`

---

draft-irtf-cfrg-vdaf.md

Closes #497.
Closes #503.
* Use "refcontent" instead of "seriesinfo". The value is a string rather than a bunch of key/value pairs. In effect, this deletes the " " before the ",".
* Put quotes around each "refcontent" value
* Replace "ins" with "name" and use the author's full name as it appears in the reference. `xml2rfc` still wants to abbreviate the first name, but we at least preserve more information.
* Add a "refcontent" for {{SML24}}.
* Reorder {{MRH04}} fields to match the other references

Clean up references

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_vdaf_poplar1.py
poc/vdaf_poc/vdaf_poplar1.py

Poplar1: Move prefix order check to is_valid()

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/field.py

This mentions in a couple places that decoding a bit representation is a linear operation, and thus we can use it in validity circuits, transparently processing secret shares of bit representations.

Mention that decode_from_bit_vec() is linear

---

poc/example_flp_shamir.py

A demonstration of the composition of FLP with Shamir's secret sharing.
This could be the basis of a Prio3 variant that tolerates drop out of an
Aggregator.
Imagine a DAP setup [1] where a Leader wants to be able to run the
protocol with one of two Helpers so that if the first Helper goes
offline, it can continue the computation with the other.
For this to work, the Client still needs to know the identities of the
two Helpers prior to generating its report.
[1] https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/22

poc: Add an example showcasing FLP with Shamir's

---

.github/workflows/lint.yml
.github/workflows/make-with-lints.sh
draft-irtf-cfrg-vdaf.md
package.json

Make the pictures pretty

---

.github/workflows/make-with-lints.sh
draft-irtf-cfrg-vdaf.md

This adds some configuration to the front matter to silence the SVG warning we're getting, and cleans up the shell script we were using to filter these out previously. See https://mailarchive.ietf.org/arch/msg/rfc-markdown/reUEfraLI_-XH7fO0wKe2ErFxno/.
This works locally, but I think we'll need to wait for a new Docker image to be built that includes kramdown-rfc 1.7.22 before it'll work in CI.

Silence SVG warning via front matter

---

draft-irtf-cfrg-vdaf.md
poc/vdaf_poc/vdaf_poplar1.py

I upgraded mypy from 1.10.0 to 1.15.0, and it found some new type errors. This PR adds another cast to Poplar1 sketching to hop between `Field64 | Field255` to `Field`.

Fix mypy errors

---

poc/tests/test_vdaf_ping_pong.py
poc/vdaf_poc/vdaf_ping_pong.py

This adds one more commit on top of the changes in #543 that I think make the API easier to use, in particular by making illegal states impossible to represent, which I believe is the overall goal here. I've left remarks throughout the diff to highlight important changes and the motivation.
I also haven't yet reflected this proposed change in the actual protocol text. It's only in the Python `poc` for now, so we can discuss whether we like it. Based on the consensus we reach, I can fix up the protocol text accordingly.

Ping pong topo

---

draft-irtf-cfrg-vdaf.md
poc/tests/test_vdaf_ping_pong.py
poc/vdaf_poc/vdaf_ping_pong.py

Closes #542.
Merge the outbound message into the Aggregator's ping pong state:
1. Remove outbound message from each API call
2. Add outbound message to `Continued`
3. Define a new state, `FinishedWithOutbound` that is like `Finished` except it include an outbound message
This reduces the number of cases the caller has to handle to only cases that are valid. In particular, the following cases are invalid:
* `state == Rejected() and outbound != None`
* `state == Continued(...) and outbound == None`

topo: Merge outbound into state

---

draft-irtf-cfrg-vdaf.md
poc/gen_test_vec.py
poc/tests/test_test_vectors.py
poc/tests/test_vdaf_ping_pong.py
poc/vdaf_poc/common.py
poc/vdaf_poc/idpf.py
poc/vdaf_poc/idpf_bbcggi21.py
poc/vdaf_poc/test_utils.py
poc/vdaf_poc/vdaf.py
poc/vdaf_poc/vdaf_ping_pong.py
poc/vdaf_poc/vdaf_poplar1.py
poc/vdaf_poc/vdaf_prio3.py

This fixes #541. I defined a suite of methods to decode various VDAF messages, and removed the `test_vec_` prefix in some cases from those methods that encoded messages. Each test vector file now has its own unit test, which runs all operations in sequence and compares against the expected results.

Add test vector tests
